/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package spring_MVCLearn

import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Test

class SpringMVCApplicationTest {
    @Test
    fun testAppHasAGreeting() {
        val classUnderTest = SpringMVCApplication()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
